import AppSidebar from '@/components/layout/app-sidebar'
import Header from '@/components/layout/header'
import { RootProvider } from '@/components/providers/root'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })

export const metadata: Metadata = { title: 'Create Next App', description: 'Generated by create next app' }

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <RootProvider>
          <AppSidebar />
          <div className='flex flex-1 flex-col'>
            <Header />
            <main className='flex flex-1 flex-col p-2'>{children}</main>
          </div>
        </RootProvider>
      </body>
    </html>
  )
}
